# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mesAssemble.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 702)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.label.setObjectName("label")
        self.craftworkBox = QtWidgets.QComboBox(self.groupBox)
        self.craftworkBox.setGeometry(QtCore.QRect(90, 40, 371, 41))
        self.craftworkBox.setObjectName("craftworkBox")
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.label_2.setObjectName("label_2")
        self.singleSn = QtWidgets.QLineEdit(self.groupBox_2)
        self.singleSn.setGeometry(QtCore.QRect(100, 40, 361, 41))
        self.singleSn.setText("")
        self.singleSn.setObjectName("singleSn")
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 131, 71))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 121, 71))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.num_job = QtWidgets.QLabel(self.groupBox_3)
        self.num_job.setGeometry(QtCore.QRect(170, 30, 301, 151))
        font = QtGui.QFont()
        font.setPointSize(86)
        self.num_job.setFont(font)
        self.num_job.setAlignment(QtCore.Qt.AlignCenter)
        self.num_job.setObjectName("num_job")
        self.num_loc = QtWidgets.QLabel(self.groupBox_3)
        self.num_loc.setGeometry(QtCore.QRect(160, 200, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(86)
        self.num_loc.setFont(font)
        self.num_loc.setAlignment(QtCore.Qt.AlignCenter)
        self.num_loc.setObjectName("num_loc")
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(20, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.multiCreateSn = QtWidgets.QPushButton(self.widget)
        self.multiCreateSn.setGeometry(QtCore.QRect(300, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.multiCreateSn.setFont(font)
        self.multiCreateSn.setObjectName("multiCreateSn")
        self.multiSn = QtWidgets.QLineEdit(self.widget)
        self.multiSn.setGeometry(QtCore.QRect(110, 10, 181, 31))
        self.multiSn.setObjectName("multiSn")
        self.multiNum = QtWidgets.QLineEdit(self.widget)
        self.multiNum.setGeometry(QtCore.QRect(110, 60, 181, 31))
        self.multiNum.setObjectName("multiNum")
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout_4.addWidget(self.btnClear, 0, 9, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 10, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        self.btnScan = QtWidgets.QPushButton(self.centralwidget)
        self.btnScan.setObjectName("btnScan")
        self.gridLayout_4.addWidget(self.btnScan, 0, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 8, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.verticalLayout_6.setStretch(0, 3)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.snTable = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        self.snTable.setFont(font)
        self.snTable.setObjectName("snTable")
        self.snTable.setColumnCount(2)
        self.snTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.snTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.snTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout_7.addWidget(self.snTable)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 10)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scada-MES装配过站"))
        self.groupBox.setTitle(_translate("MainWindow", "环境"))
        self.label.setText(_translate("MainWindow", "工艺点："))
        self.groupBox_2.setTitle(_translate("MainWindow", "过站"))
        self.label_2.setText(_translate("MainWindow", "序列号："))
        self.groupBox_3.setTitle(_translate("MainWindow", "计数"))
        self.label_3.setText(_translate("MainWindow", "工单下序列号过站个数："))
        self.label_4.setText(_translate("MainWindow", "本站实时扫描个数："))
        self.num_job.setText(_translate("MainWindow", "9999"))
        self.num_loc.setText(_translate("MainWindow", "9999"))
        self.label_6.setText(_translate("MainWindow", "起始序列号："))
        self.label_7.setText(_translate("MainWindow", "个  数："))
        self.multiCreateSn.setText(_translate("MainWindow", "生成序列号"))
        self.btnClear.setText(_translate("MainWindow", "清空"))
        self.label_5.setText(_translate("MainWindow", "操作记录："))
        self.btnScan.setText(_translate("MainWindow", "过站"))
        item = self.snTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序列号"))
        item = self.snTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "结果"))

